const OpenAI = require('openai');
const { buildPrompt } = require('./promptBuilder');
const { buildImageAssets, buildAttributionList } = require('./imageAssets');
const { generateStitchDesign } = require('./stitchService');
const { buildUnsplashImageMap } = require('./unsplashService');

let _client = null;
function getClient() {
  if (!_client) _client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  return _client;
}

async function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function generateSite(formData, attempt = 1, existingStitchDesign = null, existingUnsplashMap = null) {
  let unsplashMap  = existingUnsplashMap;
  let stitchDesign = existingStitchDesign;

  // Step 1: Fetch Pexels photos first (~3s) so Stitch gets real image URLs in its brief
  if (!unsplashMap) {
    const result = await Promise.allSettled([buildUnsplashImageMap(formData)]);
    unsplashMap = result[0].status === 'fulfilled'
      ? result[0].value
      : (() => { console.warn({ event: 'pexels_fallback', message: result[0].reason?.message }); return {}; })();
  }

  // Step 2: Build the image file map (url-type → real CDN URL, others → local path)
  // Build this early so Stitch gets the real image URLs in its design prompt.
  const imageAssets  = buildImageAssets(formData, unsplashMap);
  const attributions = buildAttributionList(imageAssets);
  const imageFileMap = Object.fromEntries(
    Object.entries(imageAssets).map(([path, asset]) => [
      asset.encoding === 'url' ? asset.url : path,
      asset.meta,
    ])
  );

  // Step 3: Call Stitch with the real image map so it can reference actual photos
  if (!stitchDesign) {
    try {
      stitchDesign = await generateStitchDesign(formData, imageFileMap);
    } catch (stitchErr) {
      console.warn({ event: 'stitch_fallback', message: stitchErr.message, attempt });
      stitchDesign = { html: null, projectId: null, screenId: null };
    }
  }

  const { system, user } = buildPrompt(formData, imageFileMap, attributions);

  const stitchInstructions = stitchDesign.html ? `

STITCH DESIGN SOURCE — REQUIRED
The HTML below was generated by Google Stitch as the approved visual design.
Rebuild it as the final deployable document while preserving its composition, hierarchy, typography,
spacing, color balance, image placement, and responsive behavior as closely as possible.

You may change implementation details only to satisfy the output, security, accessibility, and asset-path
requirements above. Remove external scripts, external stylesheets, framework runtime dependencies, and
unsafe inline event attributes. Keep all CSS and JavaScript self-contained. Use every supplied local image
asset at its exact path. Do not simplify the design into a generic landing-page template.

<stitch-html>
${stitchDesign.html}
</stitch-html>` : '';
  const promptLen = system.length + user.length + stitchInstructions.length;

  const start = Date.now();
  try {
    const response = await getClient().chat.completions.create({
      model: 'gpt-4o',
      temperature: 0.72,
      max_tokens: 8000,
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: user + stitchInstructions },
      ],
    });

    const raw = response.choices[0].message.content || '';
    const html = stripMarkdownFences(raw);
    const latencyMs = Date.now() - start;

    console.log({
      event: 'ai_generation',
      promptLen,
      responseLen: html.length,
      latencyMs,
      attempt,
      unsplashPhotos: Object.keys(unsplashMap).length,
      stitchProjectId: stitchDesign.projectId,
      stitchScreenId: stitchDesign.screenId,
    });
    return {
      html,
      imageAssets,
      imageFileMap,
      stitchProjectId: stitchDesign.projectId,
      stitchScreenId: stitchDesign.screenId,
    };
  } catch (err) {
    if (attempt < 3) {
      await sleep(1000 * attempt);
      return generateSite(formData, attempt + 1, stitchDesign, unsplashMap);
    }
    throw new Error(`OpenAI generation failed after 3 attempts: ${err.message}`);
  }
}

function stripMarkdownFences(text) {
  return text
    .replace(/^```html\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
}

module.exports = { generateSite, getClient };
